version: '2.1'
orbs:
  terraform: circleci/terraform@3.1

workflows:
  deploy_infra:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform
      - decode_tfvars:
          executor: terraform/default
          steps:
            - run:
                name: Decode and store tfvars
                command: |
                  echo "$AWS_CLOUDRESUMEBACKEND_TFVARS" | base64 --decode > $HOME/terraform.tfvars
            - attach_workspace:
                at: $HOME
      - terraform/plan:
          var_file: terraform.tfvars
          checkout: true
          context: terraform
          persist-workspace: true
          filters:
            branches:
              only: main
          requires:
            - terraform/validate
