version: '2.1'
orbs:
  terraform: circleci/terraform@3.1

jobs:
  # Decode the tfvars environment variable and save to workspace
  decode_tfvars:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo $AWS_CLOUDRESUMEBACKEND_TFVARS | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            echo $AWS_CLOUDRESUMEBACKEND_TFVARS
          name: print variable
          context: terraform

      
workflows:
  test-deploy:
    jobs:
      - decode_tfvars:
          context:
            - terraform
      
      
      
      # - attach_workspace:
      #     at: $HOME
      # - terraform/validate:
      #     checkout: true
      #     context: terraform
      # - terraform/plan:
      #     var_file: terraform.tfvars
      #     checkout: true
      #     context: terraform
      #     persist-workspace: true
