version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infra:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform
      - terraform/plan:
          var_file: AWS_CLOUDRESUMEBACKEND_TFVARS
          checkout: true
          context: terraform
          persist-workspace: true
          filters:
            branches:
              only: main
          requires:
            - terraform/validate
 
