
version: '2.1'
orbs:
  terraform: circleci/terraform@3.1

jobs:
  # Decode the tfvars environment variable and save to workspace
  decode_tfvars:
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo $AWS_CLOUDRESUMEBACKEND_TFVARS | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            ls -la
          name: Find tfvars file
          path: ..
          context: terraform
      - terraform/validate:
          path: .
      - terraform/init:
          path: .
      - terraform/plan:
          path: ..
          var_file: terraform.tfvars
   
      
workflows:
  test-deploy:
    jobs:
      - decode_tfvars:
          context:
            - terraform
      
      
    
