version: '2.1'

orbs:
  terraform: circleci/terraform@1.1.3

workflows:
  deploy_infra:
    jobs:
      - terraform/validate:
          context: terraform

      - decode_tfvars:
          docker:
            - image: circleci/python:3.7
          steps:
            - run:
                name: Decode and store tfvars
                command: |
                  echo "$AWS_CLOUDRESUMEBACKEND_TFVARS" | base64 --decode > $HOME/terraform.tfvars
            - persist_to_workspace:
                root: $HOME
                paths:
                  - terraform.tfvars

      - terraform/plan:
          var_file: terraform.tfvars
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - terraform/validate
