
version: '2.1'
orbs:
  terraform: circleci/terraform@3.1

jobs:
  # Decode the tfvars environment variable and save to workspace
  decode_tfvars:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo $AWS_CLOUDRESUMEBACKEND_TFVARS | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            cat $HOME/terraform.tfvars
          name: print variable
          context: terraform
      - run:
          command: >-
            cp $HOME/terraform.tfvars .
          name: print variable 2
          context: terraform
      - run:
          command: >-
            ls -la .
          name: print variable 3
          context: terraform
      - terraform/validate:
          path: .
      - terraform/init:
          path: .
      - terraform/plan:
          var_file: terraform.tfvars
   
      
workflows:
  test-deploy:
    jobs:
      - decode_tfvars:
          context:
            - terraform
      
      
    
