version: '2.1'

workflows:
  deploy_infra:
    jobs:
      - decode_tfvars:
          docker:
            - image: circleci/python:3.7
          steps:
            - run:
                name: Decode and store tfvars
                command: |
                  echo "$AWS_CLOUDRESUMEBACKEND_TFVARS" | base64 --decode > $HOME/terraform.tfvars
            - persist_to_workspace:
                root: $HOME
                paths:
                  - terraform.tfvars

      - terraform/validate:
          docker:
            - image: hashicorp/terraform:1.0.0
          steps:
            - attach_workspace:
                at: $HOME
            - run:
                name: Validate Terraform configuration
                command: |
                  terraform init
                  terraform validate

      - terraform/plan:
          docker:
            - image: hashicorp/terraform:1.0.0
          steps:
            - attach_workspace:
                at: $HOME
            - run:
                name: Plan Terraform changes
                command: |
                  terraform init
                  terraform plan -var-file=terraform.tfvars
